### ISSUE TITLE
[Feature request] callback enhancements 2

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#62]
I apologize for the second report, but I'm not sure if you saw my comments from the first issue because it's closed now. (I'm not very familiar with Github's issue system)
https://github.com/Noooste/azuretls-client/issues/56#issue-2187016949

I proposed that the context (context.Context, not azuretls.Context) should be exported. The fix is easy since in callbacks the new azuretls.Context object passes the azuretls.Session object which has the context assigned in its structure
![image](https://github.com/Noooste/azuretls-client/assets/49800712/48a54a7f-4a3d-4001-8499-c377b68d0ef9)

This would be very useful since I'm running a multithreaded application, when my callback is still running, and the original context gets canceled, my application crashes.

Another issue I noticed was that in the previous Callback that was deprecated, the callback would be able to return errors. How ever in the new callback. we are given a azuretls.Context object. Adjusting fields in the request and response object works, but assigning the request and response object pointer doesn't seem to change anything. After completing a request, the callback should be passed the context structure, and when the callback is finished, the objects in the context structure should be used. This would allow callbacks to set the error object, or any other object like request or response.

**Comment by Noooste** [comment]
Hello, thanks for sharing me your trouble with the client.

I'm going to modify some of the features based on what you've said:
- you'll now be able to access the session context with session.Context() or session.SetContext(ctx) to modify it.
- for the error in the callback, I'll make it adjustable so that if the callback sets an error in the context, the error will be returned in the general flow.

However, why reassign new pointers to the context when you can simply modify them on the spot? 

Also, I didn't understand this part `This would be very useful since I'm running a multithreaded application, when my callback is still running, and the original context gets canceled, my application crashes.` 
Could you elaborate?

If you can think of any other information to put into azuretls.Context, I'd be happy to take note.

**Comment by VegieIsCute** [comment]
To answer your question on why I should reassign pointers, it has to do with rate-limit handling, but can be used for many other purposes. When a rate limit is hit, my callback receives the response and well extract the necessary retry-after data or header and will wait. After a while it will repeat the request by doing context.session.Do(context.request) after this, I wrote a function to manually assign each property of the new response to the original response, It's not a dire need but it would be better if i could just assign the response from the new request to the old one out right.

Also for ``Also, I didn't understand this part This would be very useful since I'm running a multithreaded application, when my callback is still running, and the original context gets canceled, my application crashes.
Could you elaborate?`` This shouldn't be an issue after the context is exposed from the session, I haven't debugged to determine the exact cause but it is obvious that the callback is not canceling and probably continues the execution of the request even after the request has closed its connection.

**Comment by Noooste** [comment]
I will make the necessary changes to replace the answer in the context, which will save resources and avoid value copying.
