### ISSUE TITLE
[QUESTION] Default browsers

### ISSUE THREAD

**Issue by stanislav-milchev** [Noooste/azuretls-client#90]
Hello!

I'd like to ask how often do you update the default browser versions or is it a thing you are not focused on? Would you accept help and how can we help about the browser impersonation?

Cheers!

**Comment by Noooste** [comment]
Hello,

I don't often update chrome's TLS because since chrome 110, it hasn't changed. 

If you want to help me update the TLS fingerprint, you can intercept the Client Hello with Wireshark and update it in the golang code. You can also get information about the Client Hello from [tls.peet.ws](https://tls.peet.ws/).

Don't hesitate to open PR with new browser versions🙂 

Thanks for your help!
